### ISSUE TITLE
Spell Check Not Working. How do I get dictionaries?

### ISSUE THREAD

**Issue by Blushock** [jendrikseipp/rednotebook#672] opened 2023-01-20 18:13 UTC
**Describe the bug**
When I click on the edit tab and then Spell Check, the box never goes from unchecked to checked. Nor does it underline misspelled words.

**To Reproduce**
1. Click on "Edit" tab
2. Click on 'Spell Check'
3. Repeat 1 and 2
4. The box is still not checked

**Expected behavior**
Spell Check to work, the box to be checked, and misspelled words to be underlined

**Screenshots**
![Spell Check not working](https://user-images.githubusercontent.com/60056165/213774012-40c4d3bd-181f-4698-b3c0-141ad0fc0d3b.png)

**Versions:**
- RedNotebook version 2.29.3
- Win 10 Pro:

**Log output when reproducing bug**
2023-01-20 10:01:16,580 CRITICAL no dictionaries found
2023-01-20 10:01:16,581 WARNING  No spell checking dictionaries found.
2023-01-20 10:02:11,997 CRITICAL no dictionaries found
2023-01-20 10:02:11,997 WARNING  No spell checking dictionaries found.

**Comment by jendrikseipp** [comment] 2023-01-20 19:58
Thanks for the report! Unfortunately, I can't reproduce the problem. Dictionaries come bundled with RedNotebook, so there's nothing to be "fixed" there. Are you using the official .exe installer from the rednotebook.app homepage?

**Comment by frobozz-magic** [comment] 2023-04-16 22:41
I have a similar issue, or maybe the same one.  I'm running Windows 11, installed it using the official installer on rednotebook.app but the Spell Check box never comes on.  The config file shows 'spellchek=1'  and the log file says:

2023-04-16 14:59:41,664 WARNING  For spell checking, please install enchant (python3-enchant).

So I tried installing pyenchant but apparently it's already there:

C:\Users\sysgod>pip install pyenchant
Requirement already satisfied: pyenchant in c:\users\sysgod\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.2.2)

I'm not much of a python guy, so don't know what to try next.  Any help appreciated.  BTW this is a great app, been using it for years with Linux but just have this one little problem on Windows.

**Comment by Blushock** [comment] 2023-04-17 02:37
> Thanks for the report! Unfortunately, I can't reproduce the problem. Dictionaries come bundled with RedNotebook, so there's nothing to be "fixed" there. Are you using the official .exe installer from the rednotebook.app homepage?

Oh, I didn't know they came bundled. I can mess around with some stuff, see what happens. Sorry for any confusion.

**Comment by frobozz-magic** [comment] 2023-04-17 14:49
Yes, I did use the installer at rednotebook.app.  I’ve also discovered that if I install the old version 2.26 it DOES allow spell checking, but if I install version 2.27.2 is does not.  So, somewhere between those versions something happened.  Thanks for looking into this!

Sent from Mail for Windows

**Comment by dwalton65** [comment] 2023-05-29 21:56
Spell check is not working for me either

**Comment by dwalton65** [comment] 2023-05-29 22:21
As commented by [frobozz-magic](https://github.com/frobozz-magic) previously, Spell check does work with Rednotebook V2.26
Copying C:\Program Files (x86)\RedNotebook\lib\aspell-0.60 from V2.26 to V2.29.6 does not fix the problem.

**Comment by dwalton65** [comment] 2023-06-14 00:47
As a workaround I am using Rednotebook V2.26 on Ubuntu via WSL. Spell checking is working and I have been able to add Australian English dictionaries.

**Comment by kathenas** [comment] 2023-11-23 06:10
I cannot reproduce with rednotebook 2.31 (official installer) on Windows 11 Enterprise.

![Screenshot from 2023-11-23 06-04-14](https://github.com/jendrikseipp/rednotebook/assets/68813857/5a98e73a-9e93-4a13-8376-a653b5ad4903)

I think this issue should be closed and people encouraged to file new reports if they have the same or similar with 2.31 or newer.

**Comment by dkselw** [comment] 2023-11-23 06:31
Spell check is now working for me also using Rednotebook V2.31 on Windows 10 Pro

**Comment by jendrikseipp** [comment] 2023-11-24 12:16
Thanks for testing this! Let's close this then.

**Closed by jendrikseipp** 2023-11-24 12:16 UTC
Labels: bug
