### ISSUE TITLE
[Feature Request] Android/iOS App

### ISSUE THREAD

**Issue by trymeouteh** [jendrikseipp/rednotebook#384] opened 2017-11-29 02:14 UTC
RedNotebook is the best journal software on desktop computes. Especially how it shorts the file into folder by month. But an app for mobile devices would be great so we can write in your Journals on the go and even read our journals on our phone. And if it used Material Design for the Andriod app it would look quite slick!

**Comment by jendrikseipp** [comment] 2018-03-12 19:15
I agree that a mobile app would be really useful. Unfortunately, there are no plans for a mobile version at the moment.

**Comment by jendrikseipp** [comment] 2019-11-02 09:52
Duplicate of #165.

**Closed by jendrikseipp** 2019-11-02 09:52 UTC
