### ISSUE TITLE
Add Checksums to the Releases

### ISSUE THREAD

**Issue by TheClonker** [jendrikseipp/rednotebook#381] opened 2017-11-16 11:26 UTC
Meta Issue with the Repository so no Template

Hello,
i was wondering if it would be possible for you to add Checksums for your Releases on Github to verfiy the integrity of the Download ?

**Comment by jendrikseipp** [comment] 2017-11-16 11:31
I'll look into that :-)

**Comment by kathenas** [comment] 2017-11-17 18:54
This is essentially a duplicate of #363

**Comment by jendrikseipp** [comment] 2018-03-12 19:16
Closing this, since it's a duplicate.

**Closed by jendrikseipp** 2018-03-12 19:16 UTC
