### ISSUE TITLE
Default Backup Save Location on Win10?

### ISSUE THREAD

**Issue by Blushock** [jendrikseipp/rednotebook#671] opened 2023-01-20 09:19 UTC
### Discussed in https://github.com/jendrikseipp/rednotebook/discussions/670

<div type='discussions-op-text'>

<sup>Originally posted by **Blushock** January 20, 2023</sup>
Hi? On Windows 10, what is the default location RedNotebook saves backups in? I currently save them in a custom Desktop Folder, but could not find the default location or reset it.</div>

Probably should have made this an issue to begin with tbh.

**Comment by jendrikseipp** [comment] 2023-01-20 12:07
Closing this issue since it's a question, not a bug report.

**Closed by jendrikseipp** 2023-01-20 12:07 UTC
