### ISSUE TITLE
unable to open linked pdf files with french accent in filename

### ISSUE THREAD

**Issue by pimou** [jendrikseipp/rednotebook#418] opened 2018-12-05 20:18 UTC
### Versions

RedNotebook version (make sure you have the latest version): 2.5

Operating system and version: Fedora 29 Gnome (french)

### Expected behavior
all pdf linked file can be opened : with and without french accent in filename

### Actual behavior
I'am unable to open linked pdf files with french accent in filename.
Only pdf filenames without accent can be opened.

### Steps to reproduce the behavior
2 link to pdf files : (it is the same file but a filename with accent 'è' and a filename without accent)
/home/pierre/Documents/fds81044_bleu_de_methylene.pdf
/home/pierre/Documents/fds81044_bleu_de_methylène.pdf

Links in rednotebook :
[fds81044_bleu_de_methylene.pdf ""file:///home/pierre/Documents/fds81044_bleu_de_methylene.pdf""]
[fds81044_bleu_de_methylène.pdf ""file:///home/pierre/Documents/fds81044_bleu_de_methylène.pdf""]
First link is working : trace in log file. Second link is not working : no trace in log file.

### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
2018-12-05 21:09:32,111 INFO     Writing log to file "/home/pierre/.rednotebook/rednotebook.log"
2018-12-05 21:09:32,111 INFO     System encoding: utf-8
2018-12-05 21:09:32,111 INFO     Language code: fr_FR
2018-12-05 21:09:32,275 INFO     Running in portable mode: False
2018-12-05 21:09:32,275 INFO     First Start: False
2018-12-05 21:09:32,275 INFO     RedNotebook version: 2.5
2018-12-05 21:09:32,280 INFO     System info: machine: x86_64, platform: Linux-4.19.5-300.fc29.x86_64-x86_64-with-fedora-29-Twenty_Nine, processor: x86_64, python_version: 3.7.1, release: 4.19.5-300.fc29.x86_64, system: Linux, GTK: (3, 24, 1), Glib: (2, 58, 1), PyGObject: (3, 30, 4), YAML: 4.2
2018-12-05 21:09:32,525 DEBUG    Default font: Ubuntu 11.5
2018-12-05 21:09:32,525 DEBUG    Default size: 11.5
2018-12-05 21:09:32,708 INFO     Cloud ignore list: ['filter', 'these', 'comma', 'separated', 'words', 'and', '#tags']
2018-12-05 21:09:32,708 INFO     Cloud include list: ['tf1', 'note', 'vite', 'job', 'jeu']
2018-12-05 21:09:32,708 DEBUG    Start compiling regexes
2018-12-05 21:09:32,709 DEBUG    Finished
2018-12-05 21:09:32,719 DEBUG    Tray icon visible: False
2018-12-05 21:09:32,719 INFO     Opening journal at '/home/pierre/Documents/Rednotebook'
2018-12-05 21:09:32,720 DEBUG    Starting to load files in dir "/home/pierre/Documents/Rednotebook"
2018-12-05 21:09:32,720 DEBUG    Loading file "/home/pierre/Documents/Rednotebook/2018-11.txt"
2018-12-05 21:09:32,720 DEBUG    Loading file "/home/pierre/Documents/Rednotebook/2018-12.txt"
2018-12-05 21:09:32,721 DEBUG    Finished loading files in dir "/home/pierre/Documents/Rednotebook"
2018-12-05 21:09:32,726 DEBUG    Add mathjax code: False
2018-12-05 21:09:32,731 INFO     Connected Signals: [<Signals.SIGHUP: 1>, <Signals.SIGINT: 2>, <Signals.SIGQUIT: 3>, <Signals.SIGABRT: 6>, <Signals.SIGTERM: 15>, <Signals.SIGTSTP: 20>]
2018-12-05 21:09:32,731 DEBUG    Start took 0.456881046295166 seconds
2018-12-05 21:09:32,731 DEBUG    Trying to enter the gtk main loop
2018-12-05 21:09:32,797 DEBUG    Update the cloud
2018-12-05 21:09:32,799 DEBUG    Cloud updated
2018-12-05 21:09:32,802 INFO     Last backup was made -2915026 days ago
2018-12-05 21:09:34,577 INFO     Clicked URI "file:///home/pierre/Documents/fds81044_bleu_de_methylene.pdf"
2018-12-05 21:09:34,577 INFO     Trying to open file:///home/pierre/Documents/fds81044_bleu_de_methylene.pdf with xdg-open
2018-12-05 21:09:41,317 DEBUG    Main frame destroyed
2018-12-05 21:09:41,320 INFO     Rien à sauvegarder
2018-12-05 21:09:41,320 INFO     Goodbye!
2018-12-05 21:09:41,327 INFO     Peak memory: 134900604 KiB

**Comment by carnendil** [comment] 2019-04-04 19:19
I can confirm the same behaviour on Ubuntu 16.04.1 using RedNotebook 2.11, and I think this is related to, or the same problem as, #331 .

**Comment by jendrikseipp** [comment] 2022-11-20 09:09
I'm closing this issue for now, since there hasn't been any recent activity. Feel free to reopen it if the issue persists in the latest RedNotebook version.

**Closed by jendrikseipp** 2022-11-20 09:09 UTC
