### ISSUE TITLE
Hash Symbol breaks out of URL mode

### ISSUE THREAD

**Issue by Haizo** [jendrikseipp/rednotebook#625] opened 2022-06-08 05:45 UTC
**Describe the bug**
When a URL contains '#' it drops out of URL mode (expecting hashtag?) and the remainder is plain text

**To Reproduce**
Pasting a URL with an embedded '#' symbol, for example a postal tracking URL 
https://auspost.com.au/mypost/track/#/details/JQR5070715  (not a real parcel code)

**Expected behaviour**
I would hope to see the full URL to ensure that I copy it correctly when looking up pending deliveries etc.
Once you start displaying a URL, I would only expect to stop for WhiteSpace or NewLine.

**Screenshots**
![image](https://user-images.githubusercontent.com/636733/172538093-33d67d7b-c30d-446d-ab1b-e210bf4f6452.png)

**Versions:**
- RedNotebook version 2.25
- Operating system and version: Windows 10 Pro 21H2
OS Build:  19044.1706
Experience:  Windows Feature Experience Pack 120.2212.4170.0

**Log output when reproducing bug**
N/A

**Comment by jendrikseipp** [comment] 2022-12-29 22:50
Duplicate of #556.

**Closed by jendrikseipp** 2022-12-29 22:50 UTC
Labels: bug
