### ISSUE TITLE
Please follow the XDG Base Directory Specification and store config in $HOME/.config or $XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by carygravel** [jendrikseipp/rednotebook#538] opened 2020-10-11 13:53 UTC
**Describe the bug**
The .rednotebook directory pollutes the home directory. It would be better to adhere to standards and put it in ~/.config (and possibly $HOME/.local/share)

There are also Windows equivalents for these directories.

**Comment by jendrikseipp** [comment] 2020-10-11 17:33
Duplicate of #404

**Closed by jendrikseipp** 2020-10-11 17:33 UTC
Labels: bug
