### ISSUE TITLE
Statistuc

### ISSUE THREAD

**Issue by tossia** [jendrikseipp/rednotebook#431] opened 2019-03-25 21:14 UTC
![image](https://user-images.githubusercontent.com/34798428/54952575-935a8980-4f46-11e9-84d0-d3872a57aad1.png)
### Versions 
RedNotebook version (make sure you have the latest version): 2.6.1
Operating system and version: Windows 10 64
### Log output when reproducing behavior

Please paste contents from $HOME/.rednotebook/rednotebook.log,
where $HOME is usually C:\Users\<username> on Windows.
2019-03-25 20:56:19,483 INFO     Writing log to file "C:\Users\tossi\RedNotebookPortable\App\RedNotebook\../../Data/usersettings\rednotebook.log"
2019-03-25 20:56:19,483 INFO     System encoding: mbcs
2019-03-25 20:56:19,483 INFO     Language code: fr_FR
2019-03-25 20:56:19,541 INFO     Using pyyaml for loading and dumping
2019-03-25 20:56:19,764 INFO     Running in portable mode: True
2019-03-25 20:56:19,764 INFO     First Start: False
2019-03-25 20:56:19,764 INFO     RedNotebook version: 2.6.1
2019-03-25 20:56:19,769 INFO     System info: machine: AMD64, platform: Windows-10-10.0.17134-SP0, processor: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel, python_version: 3.4.4, release: 10, system: Windows, GTK: (3, 18, 9), Glib: (2, 52, 1), PyGObject: (3, 18, 2), YAML: 3.10
2019-03-25 20:56:20,819 DEBUG    Default font: Sans 10
2019-03-25 20:56:20,819 DEBUG    Default size: 10.0
2019-03-25 20:56:21,042 DEBUG    Tray icon visible: False
2019-03-25 20:56:21,046 INFO     Opening journal at 'C:\\Users\\tossi\\RedNotebookPortable\\Data\\usersettings\\data'
2019-03-25 20:56:21,046 DEBUG    Starting to load files in dir "C:\Users\tossi\RedNotebookPortable\Data\usersettings\data"
2019-03-25 20:56:21,047 DEBUG    Loading file "C:\Users\tossi\RedNotebookPortable\Data\usersettings\data\2019-03.txt"
2019-03-25 20:56:21,060 DEBUG    Finished loading files in dir "C:\Users\tossi\RedNotebookPortable\Data\usersettings\data"
2019-03-25 20:56:21,067 INFO     Connected Signals: [2, 22, 15]
2019-03-25 20:56:21,068 DEBUG    Start took 1.304203987121582 seconds
2019-03-25 20:56:21,068 DEBUG    Trying to enter the gtk main loop
2019-03-25 20:56:21,205 INFO     Last backup was made 0 days ago
2019-03-25 20:59:49,470 DEBUG    Add mathjax code: True
2019-03-25 21:04:19,999 DEBUG    Add mathjax code: False
2019-03-25 21:04:34,466 DEBUG    Add mathjax code: False
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
2019-03-25 21:36:49,892 WARNING  no installed dictionary for language "fr_FR", fallback to english
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
2019-03-25 21:46:20,943 INFO     Configuration has been saved to C:\Users\tossi\RedNotebookPortable\App\RedNotebook\../../Data/usersettings\configuration.cfg
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.
--- Logging error ---
Traceback (most recent call last):
  File "C:\Python34\lib\logging\__init__.py", line 980, in emit
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\util\utils.py", line 168, in write
  File "C:\Python34\lib\encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 33-38: character maps to <undefined>
Call stack:
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 588, in <module>
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 577, in main
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 318, in save_to_disk
  File "Z:\home\jendrik\data\projects\RedNotebook\dist\drive_c\rednotebook\rednotebook\journal.py", line 476, in show_message
  File "C:\Python34\lib\logging\__init__.py", line 1859, in log
  File "C:\Python34\lib\logging\__init__.py", line 1346, in log
  File "C:\Python34\lib\logging\__init__.py", line 1414, in _log
  File "C:\Python34\lib\logging\__init__.py", line 1424, in handle
  File "C:\Python34\lib\logging\__init__.py", line 1486, in callHandlers
  File "C:\Python34\lib\logging\__init__.py", line 853, in handle
  File "C:\Python34\lib\logging\__init__.py", line 984, in emit
Unable to print the message and arguments - possible formatting error.
Use the traceback above to help find the error.

**Comment by jendrikseipp** [comment] 2019-03-26 18:33
I guess this is a duplicate of #370 .

**Closed by jendrikseipp** 2019-03-26 18:33 UTC
