### ISSUE TITLE
cloudMaxTags is reset to 0 when reopening the settings dialog

### ISSUE THREAD

**Issue by jendrikseipp** [jendrikseipp/rednotebook#461] opened 2019-11-06 19:36 UTC
@idle-code Can you have a look, please?

**Comment by idle-code** [comment] 2019-11-07 07:20
I'm afraid I cannot reproduce this. I have tried setting this limit to both zero and few tags - it just keeps the old value whenever I open settings dialog multiple times in one session or after closing the app.
There is one place where it could be set to 0 - line 123 in `gui/options.py`:
``value = Option.config.read(option_name, default)  #where default is 0``

Do you have `cloudMaxTags` saved in your configuration file?

**Closed** 2019-11-07 10:57 UTC

**Comment by jendrikseipp** [comment] 2019-11-07 10:59
It seems we needed to set the value explicitly.
